# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-30 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pic',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to='static/core/files/'),
        ),
    ]
