# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-01 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180701_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pic',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
