# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-01 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180701_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_pic',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
