# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-01 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_pic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_pic',
            name='name',
        ),
    ]
