# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-01 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_user_pic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/messages/')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='picture',
        ),
        migrations.AddField(
            model_name='messagefile',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Message'),
        ),
    ]
