# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180701_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media/messages/'),
        ),
    ]
