# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-01 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180701_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagefile',
            name='message',
        ),
    ]
